baseURL: "https://dB2510.github.io/"
languageCode: "en-us"
title: "dhruv"
theme: personal-theme
relativeurls: true

Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: "0xdhruv"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav/favicon.ico"

  theme:
    disableThemeToggle: false
    defaultTheme: "dark"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Dhruv Bodani."
    subtitle: "Let's BUIDL"
    content: "A passionate Full Stack Protocol Engineer. I tend to make use of cutting edge technologies to build and ship products for the decentralised web."
    image: /images/pfp.jpeg
    # button:
    #   enable: true
    #   name: "Resume"
    #   url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/dB2510
        - icon: fab fa-twitter
          url: https://twitter.com/dhruvbodani
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/dhruv-bodani/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/pfp-circle.png"
    content: |-
      I am a software engineer with a passion for blockchains and applied cryptography. I have a background in computer science and cryptography, and I have a strong interest in the intersection of technology and economics. I am currently working as a software engineer at [Obol Labs](https://obol.tech). 

      At Obol, we are solving hard problems of applied cryptography and distributed systems to enable Distributed Validator Technology.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Golang"
        - "Solidity"
        - "Distributed Systems"
        - "Docker"
        - "Kubernetes"
        - "Javascript"
        - "Typescript"

  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineer"
        company: "Obol Labs"
        companyUrl: "https://obol.tech"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "Learn more"
          url: "https://docs.obol.tech"
        content: "I am currently working as a software engineer at [Obol Labs](https://obol.tech). I am currently working on charon which is the client software to create distributed validators.
        Obol is on the pursuit of making Proof Of Stake world of blockchains as decentralized as possible. With distributed validator technology (DVT) we will enable more decentralization, more availability and less slashings."

      - job: "Software Developer"
        company: "Atlassian"
        companyUrl: "https://www.atlassian.com/"
        date: "Jul 2021 - Dec 2021"
        info:
          enable: false
        content: |
          I worked at Atlassian as a Software Developer in Bengaluru, India. I was part of Commerce team at Atlassian which is responsible for Order Management, Subscription, Promotions, etc microservices across all the products offered by Atlassian.

      - job: "Blockchain Engineering Intern"
        company: "Nethermind"
        companyUrl: "https://nethermind.io/"
        date: "Oct 2021 - Dec 2021"
        info:
          enable: false
        featuredLink:
          enable: true
          name: "Learn more"
          url: "https://github.com/NethermindEth/nethermind"
        content: |
          I was part of Eth1 team which is responsible for the development of Ethereum Execution client in .NET . Explored Ethereum, Protocol Engineering, MEV, etc. I also had the opportunity to interact with some of the brilliant minds in the space from Nethermind.

      - job: "Web3 Intern"
        company: "Coinfantasy"
        companyUrl: "https://www.coinfantasy.io/"
        date: "Aug 2021 - Oct 2021"
        info:
          enable: false
        content: |
          - Wrote smart contracts in solidity and deployed on rinkeby, polygon mumbai testnet, etc.
          - Worked with building subgraphs using The Graph protocol and Covalend APIs to query various network chains.

      - job: "Software Engineer Intern"
        company: "Xook"
        companyUrl: "https://xook.io/"
        date: "Mar 2021 - Jun 2021"
        info:
          enable: false
        content: |
          - Worked on the server infrastructure of a Cooking Robot.
          - Developed and managed 7 different microservices that handles user profiles, order management, fulfillment, machine inventory, etc.
          - Worked on the integrations of REST APIs with React Native Application.

      - job: "Full Stack Engineer"
        company: "Smylo"
        date: "Sep 2020 - Feb 2021"
        info:
          enable: false
        content: |
          - Build APIs using NodeJS and Typescript for multiple Smylo services.
          - Designed backend architecture including usage of AWS services like EC2, RDS, S3, etc.

  # Education
  # education:
  #   enable: true
  #   # index: true
  #   items:
  #     - title: "Bachelor of Technology in Computer Science"
  #       school:
  #         name: "National Institute of Technology, Tiruchirappalli"
  #         url: "https://nitt.edu"
  #       date: "2017 - 2021"
  #       content: |-
  #         I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
  #         - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
  #         - Face mask detection using a single convolutional neural network.

  #         Extracurricular Activities
  #           - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
  #           - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
  #       featuredLink:
  #         enable: true
  #         name: "My academic record"
  #         url: "https://example.com"
  #     - title: "High School"
  #       school:
  #         name: "Thomas Jefferson High School for Science and Technology."
  #         url: "https://example.org"
  #       GPA: "4.2 out of 5.0"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"

  # Achievements
  # achievements:
  #   enable: true
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  # projects:
  #   enable: true
  #   items:
  #     - title: Hugo Profile
  #       content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
  #       image: /images/projects/profile.png
  #       featured:
  #         name: Demo
  #         link: https://hugo-profile.netlify.app
  #       # badges:
  #       #   - "Hugo"
  #       #   - "Bootstrap"
  #       #   - "Javascript"
  #       links:
  #         - icon: fa fa-envelope
  #           url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/hugo-profile
  #         - icon: fab fa-twitter
  #           url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

  #     - title: Image Converter
  #       content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
  #       image: /images/projects/converter.jpg
  #       featured:
  #         name: Demo
  #         link: https://django-converter.herokuapp.com
  #       # badges:
  #       #   - "Django"
  #       #   - "Bootstrap"
  #       links:
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/converter

  #     - title: Hugo Profile V2
  #       content: A clean and simple Hugo template for personal portfolio and blog.
  #       image: /images/projects/profile2.jpg
  #       featured:
  #         name: Demo V2
  #         link: https://hugo-profile-2.netlify.app
  #       # badges:
  #       #   - "Hugo"
  #       #   - "Bootstrap"
  #       #   - "Javascript"
  #       links:
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: dhruvbodani2510@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/dB2510
      linkedin: https://www.linkedin.com/in/dhruv-bodani/
      twitter: https://twitter.com/dhruvbodani
